# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Colten Appleby
title: Software Engineer
email: colten.appleby@gmail.com
website: www.appleby.dev

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  coltenappleby
# stackoverflow_username: "00000001"
# instagram_username: jameswgrant
linkedin_username: colten-appleby

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  I am a seasoned software engineer, and I specialize in developing user-centric products. 
  My strength lies in understanding and analyzing user interactions with technology, ensuring that the end result meets their needs effectively. 
  I am in search of a team that embraces collaboration and innovative thinking, where mutual challenges propel skill development, and a shared commitment to quality and exceptional products is the norm. 
  I am seeking an in-person/hybrid position to contribute my skills to a dynamic and collaborative work environment.
  The things that I currently have the most experience working with are:
  <mark>ES6 Javascript</mark>,
  <mark>React</mark>,
  <mark>Python</mark>,
  <mark>Java Spring Boot</mark>,
  <mark>PostgreSQL</mark>, and
  <mark>git</mark>.

content:
  - title: Skills # Title for the section
    layout: text
    content: | # Markdown supported
      <mark> </mark> | <mark> 
      Proficient Languages: <mark>Python</mark> | <mark>React</mark> | <mark>JavaScript Java</mark> | <mark>Spring Boot</mark> | <mark>TypeScript</mark> | <mark>d3.js</mark> | <mark>Ruby</mark> | <mark>Ruby on Rails</mark> | <mark>Git (Github)</mark> | <mark>SQL</mark> | <mark>PostgreSQL</mark>
      Software: <mark>Palantir Foundry</mark> | <mark>SAP ByDesign</mark> | <mark>QGIS</mark> | <mark>Revit</mark> | <mark>Navisworks</mark>
      Technology: Machine Learning | REST | MVC | LEAN | ETL | Microservice Architecture
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    border: strong # Border between sections (none/weak/strong)
    content:
      - layout: left
        border: weak
        title: Katalyst Digital Infrastructure
        link: https://katalystdi.com
        link_text: katalystdi.com
        sub_title: Data Engineer to Software Engineer
        caption:  2021 - 2023        
        description: | # markdown supported after
          Spearheaded frontend (React) and backend (Java Spring Boot) development of responsive notification system for project permissions. Partnered with the Project Manager to enhance user experience and technical processes.  Reduced user time by ~60%. 
          
          Engineered and tested 15 Java Spring Boot API (REST & GraphQL) endpoints for package schedule tracking module. Track products from bidding through logistics and installation on-site. Iterative development with the client-facing service team. Drove 30% growth in customer acquisition. 

          Designed and developed a private NPM package (React, Typescript) for visualizing and planning $500 million in construction schedules. Data visualizations included Gantt Chart and Bar Charts.
          
          Led data onboarding for construction teams of Fortune 100 hyperscalers. Aggregating over 30 TBs of data producing insights that lead to $50mm in savings. (Python, PySpark, Palantir Foundry)

      # - layout: left
      #   sub_title: Full-Stack Developer
      #   caption: November 2021 - Present        
      #   description: | # markdown supported after
      #     - Engineered 15 robust API endpoints employing REST and GraphQL paradigms using Java's Spring Boot, while also contributing significantly to a smooth transition towards a .NET microservice architecture
      #     - Built React and TypeScript components for KDI's web platform, contributing to its functionality and user experience
      #     - Developed a private NPM package for data visualization using React, Typescript and d3.js in Katalyst’s web platform
      
      - layout: left
        border: weak
        title: WR Liggett LLC
        sub_title: ERP Technology Integrator
        caption: January 2021 - November 2021        
        description: | # markdown supported after
          Orchestrated the migration of a legacy PostgreSQL database to a new ERP system. Data cleaning and conversion with Python.
          
          Implemented a $50mm SAP Business ByDesign ERP, contributing to the overall efficiency and organization of the company's operations.

      - layout: left
        title: WeWork
        sub_title: ERP Systems Integration Project Manager
        caption: May 2017 - December 2020        
        description: | # markdown supported after
          Promoted from Intern to Analyst to Associate to Lead.

          Implemented a $20mm SAP Business ByDesign ERP system for the supply chain, manufacturing, and financial systems. Co-launched a 70 person manufacturing and prefabrication subsidiary. 
          
          Developed and presented a model (python) of a $100 million supply chain to leadership, leading to successful implementation of staff leveling and a $5 million reduction in raw material spend.
          
          Formed WeWork’s Construction Technology Studio to lower construction costs through data analytics, field technology, and Building Information Management (BIM). Built a team of 25 members. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rensselaer Polytechnic Institute
        caption: 2014 - 2018
        sub_title: BSc Industrial Engineering
        description: | # markdown supported after
          Organizations: Varsity Cross-Country Team, Lambda Chi Alpha, Club Badminton
      - layout: left
        title: Georgia Institute of Technology
        caption: Expected 2025
        sub_title: Online Masters of Science in Computer Science - OMSCS
        description: |
          Relevant Classes: Machine Learning for Trading, Machine Learning (Spring 2024)
      - layout: left
        title: Flatiron Bootcamp
        caption: 2021
        sub_title:  Full Stack Web Development Coding Bootcamp (15 Weeks)
        description: | # markdown supported after
          Five group projects in JavaScript, Ruby on Rails, React, Ruby, HTML, CSS, & SQL

  - title: A Little More About Me
    layout: text
    content: | # Markdown supported
      Alongside my interests in software and data engineering some of my other interests and hobbies are:
      <mark>Baseball</mark>, 
      <mark>Sabermetrics</mark>,
      <mark>Skiing</mark>,
      <mark>Craft Beer</mark>,
      <mark>Running</mark>,
      <mark>Hiking</mark>,
      <mark>Photography</mark>,
      <mark>Travelling</mark>,
      <mark>Pitch</mark>.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
