# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Colten Appleby
title: Integration Engineer
email: colten.appleby@gmail.com
website: www.appleby.dev

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  coltenappleby
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: colten-appleby
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  I am most skilled in: <mark>Javascript</mark>, <mark>Python</mark> & <mark>skiing</mark>.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Katalyst.DI
        link: https://katalystdi.com
        # link_text: boringcompany.com
        sub_title: Integration Engineer
        caption: November 2021 - Present
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          Designed and implemented bidirectional data pipelines that extract, transform, and load (ETL) data from Katalyst.DI`s construction supply chain platform, customer, and public sources utilizing Palantir Foundry
          Built PySpark python transformations to transform raw data to backing datasets for robust ontological object sets to extract actionable intelligence
          Facilitated data exchange across different systems including Autodesk BIM360, Procore, Google Sheets, Airtable, KDI platform, and Palantir Foundry
          Developed NPM package for charts and graphs in React and d3.js. Built various components for KDI's web platform in React and TypeScript. Helped migrate the data microservice from Java Spring Boot to .NET

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rensselaer Polytechnic Institute
        caption: 2014 - 2018
        sub_title: BSc Industrial Engineering
        quote: >
          Why not Change the World?
        description: | # this will include new lines to allow paragraphs
          Organizations: Varsity Cross-Country Team, Lambda Chi Alpha, Club Badminton

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software and data engineering some of my other interests and hobbies are:
      - Baseball
      - Sabermetrics
      - Running
      - Skiing
      - Hiking
      - Photography
      - Travelling

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
